In [4]:
import numpy as np
import pandas as pd

df = pd.read_csv('movies_2.csv') # Gathering data
df.head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."

show the movies with more than 7 in Rating & greater than 50 million Gross

In [56]:
import numpy as np
import pandas as pd

df = pd.read_csv('movies_2.csv') 
df.head(5)

print(df.shape)

print(df.info())

print(df.isna())

(616, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MovieID       616 non-null    int64
 1   Title         615 non-null    object
 2   MPAA Rating   615 non-null    object
 3   Budget        615 non-null    float64
 4   Gross         615 non-null    float64
 5   Release Date  615 non-null    object
 6   Genre         615 non-null    object
 7   Runtime       615 non-null    float64
 8   Rating        508 non-null    float64
 9   Rating Count  508 non-null    float64
 10  Summary       496 non-null    object
dtypes: float64(5), int64(1), object(5)
memory usage: 53.1+ KB
None
     MovieID  Title  MPAA Rating  Budget  Gross  Release Date  Genre  Runtime  \
0      False  False        False   False  False         False  False    False
1      False  False        False   False  False         False  False    False
2      False  False        False   False  False         False  False    False
3      False  False        False   False  False         False  False    False
4      False  False        False   False  False         False  False    False
..       ...    ...          ...     ...    ...           ...    ...      ...
611    False  False        False   False  False         False  False    False
612    False  False        False   False  False         False  False    False
613    False  False        False   False  False         False  False    False
614    False  False        False   False  False         False  False    False
615    False   True         True    True   True          True   True     True

     Rating  Rating Count  Summary
0     False         False    False
1     False         False    False
2     False         False    False
3     False         False    False
4     False         False    False
..      ...           ...      ...
611    True          True     True
612    True          True     True
613    True          True     True
614    True          True     True
615    True          True     True

[616 rows x 11 columns]

show the movies with more than 7 in Rating & greater than 50 million Gross

In [62]:
import numpy as np
import pandas as pd
df
df[(df['Gross'] > 50000000) & (df['Rating'] > 7)]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
...,...,...,...,...,...,...,...,...,...,...,...
505,506,Big Hero 6,PG,165000000.0,652105443.0,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...
506,507,Interstellar,PG-13,165000000.0,675120017.0,2014-11-05,Science Fiction,169.0,8.6,1343549.0,A team of explorers travel through a wormhole ...
507,508,Captain America: The Winter Soldier,PG-13,170000000.0,714766572.0,2014-03-20,Action,136.0,7.7,685903.0,As Steve Rogers struggles to embrace his role ...
508,509,Dawn of the Planet of the Apes,PG-13,170000000.0,710644566.0,2014-06-26,Science Fiction,130.0,7.6,395425.0,A growing nation of genetically evolved apes l...
509,510,Guardians of the Galaxy,PG-13,170000000.0,773328629.0,2014-07-30,Action,121.0,8.0,978222.0,A group of intergalactic criminals must pull t...

show the movies with more than 7 in Rating & greater than 50 million Gross & with Parental guidance as MPAA Rating

In [66]:
import numpy as np
import pandas as pd
df
df[(df['Gross'] > 50000000) & (df['Rating'] > 7) & (df['MPAA Rating'])]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
...,...,...,...,...,...,...,...,...,...,...,...
505,506,Big Hero 6,PG,165000000.0,652105443.0,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...
506,507,Interstellar,PG-13,165000000.0,675120017.0,2014-11-05,Science Fiction,169.0,8.6,1343549.0,A team of explorers travel through a wormhole ...
507,508,Captain America: The Winter Soldier,PG-13,170000000.0,714766572.0,2014-03-20,Action,136.0,7.7,685903.0,As Steve Rogers struggles to embrace his role ...
508,509,Dawn of the Planet of the Apes,PG-13,170000000.0,710644566.0,2014-06-26,Science Fiction,130.0,7.6,395425.0,A growing nation of genetically evolved apes l...
509,510,Guardians of the Galaxy,PG-13,170000000.0,773328629.0,2014-07-30,Action,121.0,8.0,978222.0,A group of intergalactic criminals must pull t...

show the count of Animation movies with more than 7 in Rating (use the shape() method)

In [ ]:
import numpy as np
import pandas as pd


df[
    (df['Genre'] == 'Animation')& (df['Rating'] > 7)
].shape [0]

#df['genre'] == 'Animation'

39

show the top 5 movies based on Budget

In [101]:
df.sort_values(by='Budget', ascending=False)[:5]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
594,595,Avengers: Infinity War,PG-13,400000000.0,2.048000e+09,2018-04-23,Action,149.0,NaN,NaN,NaN
454,455,Pirates of the Caribbean: On Stranger Tides,PG-13,380000000.0,1.045714e+09,2011-05-14,Action,136.0,6.6,455211.0,Jack Sparrow and Barbossa embark on a quest to...
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
574,575,Star Wars: The Last Jedi,PG-13,317000000.0,1.333000e+09,2019-12-09,Science Fiction,152.0,NaN,NaN,NaN
375,376,Pirates of the Caribbean: At World's End,PG-13,300000000.0,9.610000e+08,2007-05-19,Adventure,169.0,7.1,565402.0,"Captain Barbossa, Will Turner and Elizabeth Sw..."

KeyError: 'Genre'